# Generated by Django 6.0.4 on 2026-05-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_project_transaction_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("resource", "Resource"),
                    ("finance", "Finance"),
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                ],
                default="finance",
                max_length=30,
            ),
        ),
    ]
